// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDblLajpfPbPhGy9r5g5MGvKVokwqwU9jw',
    appId: '1:813736249482:web:343da989074164f2798573',
    messagingSenderId: '813736249482',
    projectId: 'legally-ai3',
    authDomain: 'legally-ai3.firebaseapp.com',
    storageBucket: 'legally-ai3.firebasestorage.app',
    measurementId: 'G-94CTNZXVEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1X6jfg3drgTjXnlY2Wa9_BkdASRqVBro',
    appId: '1:813736249482:android:80b915a350cfd527798573',
    messagingSenderId: '813736249482',
    projectId: 'legally-ai3',
    storageBucket: 'legally-ai3.firebasestorage.app',
  );
}
